### PR TITLE
Add field to save OriginalOperatorNumeric in CellInfoGsm

### PR DESCRIPTION
**Pull request by cheah**
Fix for phhusson/treble_experimentations#486

### CODE REVIEW

**Review by penn5 — COMMENTED** [review]
I'd go for @UnsupportedAppUsage rather than @hide.

**Comment by phhusson** [comment]
I think hide is the only way not to break the API?

**Comment by penn5** [comment]
Or both?

**Comment by cheah** [comment]
Added `@UnsupportedAppUsage`.
The correct way seems to be having both: `@hide` to prevent Javadoc generation & `@UnsupportedAppUsage` to [restrict app usages](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces).

**Comment by cheah** [comment]
Urgh. Removed `@UnsupportedAppUsage` as it doesn't exist in Pie. It was introduced in Q.

**Comment by phhusson** [comment]
Oh I forgot this sorry. 
Why is `@hide` commented?

**Comment by cheah** [comment]
It's a Javadoc attribute :smile: Hence it's commented.

**Comment by penn5** [comment]
...? It got merged?

**Pull request closed without merging**
